language: java
jdk:
  - oraclejdk8
install: mvn -Psvg,tutorial,svm,uncertain -DskipTests=true -Dmaven.javadoc.skip=true -B -V clean install
script: mvn -Pcodecov -DskipTests=false -Dmaven.javadoc.skip=true -B -V test
before_install: pip install --user codecov
after_success: codecov
